# Generated by Django 5.2 on 2025-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BikeRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                (
                    "bike_type",
                    models.CharField(
                        choices=[
                            ("mountain", "Xe đạp leo núi"),
                            ("road", "Xe đạp đường trường"),
                            ("electric", "Xe đạp điện"),
                            ("kids", "Xe đạp trẻ em"),
                            ("assist", "Xe đạp trợ lực"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("pickup_date", models.DateField()),
                ("return_date", models.DateField()),
                ("message", models.TextField(blank=True)),
                ("rental_code", models.CharField(max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "verbose_name": "Đơn thuê xe",
                "verbose_name_plural": "Đơn thuê xe",
            },
        ),
    ]
