# Generated by Django 5.2 on 2025-12-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Hình ảnh')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('short_description', models.TextField(verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên cửa hàng')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giờ mở cửa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Store/', verbose_name='Hình ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Danh sách cửa hàng',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
