# Generated by Django 5.2 on 2025-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
