# Generated by Django 5.2 on 2025-12-01 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_bikerental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mẫu xe')),
                ('bike_type', models.CharField(choices=[('mountain', 'Xe đạp leo núi'), ('road', 'Xe đạp đường trường'), ('electric', 'Xe đạp điện'), ('kids', 'Xe đạp trẻ em'), ('assist', 'Xe đạp trợ lực')], max_length=20, verbose_name='Loại xe')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá thuê/giờ (VNĐ)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xe đạp',
                'verbose_name_plural': 'Danh sách xe đạp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bikerental',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn thuê xe', 'verbose_name_plural': 'Đơn thuê xe'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AddField(
            model_name='bikerental',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Tổng tiền'),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thuê'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='bike_type',
            field=models.CharField(choices=[('mountain', 'Xe đạp leo núi'), ('road', 'Xe đạp đường trường'), ('electric', 'Xe đạp điện'), ('kids', 'Xe đạp trẻ em'), ('assist', 'Xe đạp trợ lực')], max_length=20, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='message',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='pickup_date',
            field=models.DateField(verbose_name='Ngày nhận'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='rental_code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Mã đơn'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='return_date',
            field=models.DateField(verbose_name='Ngày trả'),
        ),
        migrations.AlterField(
            model_name='bikerental',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('renting', 'Đang thuê'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.bike', verbose_name='Xe đạp'),
        ),
    ]
